#!/bin/bash
# check-render-env.sh
# Check what environment variables are actually set on Render

echo "🔍 CHECKING RENDER ENVIRONMENT VARIABLES"
echo "========================================"

echo ""
echo "📋 Current .env file contents:"
echo "-----------------------------"
grep -E "^[A-Z_].*=" backend/.env | head -10

echo ""
echo "🚨 RENDER.COM ENVIRONMENT VARIABLE ISSUE"
echo "========================================"
echo ""
echo "❌ Problem: API keys showing 401 Unauthorized"
echo "❌ Cause: Environment variables not deployed to Render.com"
echo "❌ Issue: .env file is local only - Render needs manual env var setup"
echo ""
echo "✅ SOLUTION: Set environment variables in Render Dashboard"
echo ""
echo "📋 REQUIRED ACTIONS:"
echo "1. Go to: https://dashboard.render.com"
echo "2. Click your 'go-barry' service"
echo "3. Go to 'Environment' tab"
echo "4. Add these environment variables:"
echo ""
echo "   TOMTOM_API_KEY=9rZJqtnfYpOzlqnypI97nFb5oX17SNzp"
echo "   HERE_API_KEY=55brLMetn_8TR0ghfLG3xFfaObY9jhPpu0XEb-W4_KQ"
echo "   MAPQUEST_API_KEY=OeLAVWPNIgnBjW66iam0yiD5kEecJl0N"
echo "   NATIONAL_HIGHWAYS_API_KEY=d2266b385f64d968f330969398b2961"
echo ""
echo "5. Click 'Save Changes'"
echo "6. Wait for automatic redeploy (2-3 minutes)"
echo "7. Test again: node detailed-source-test.js"
echo ""
echo "🎯 Expected result after fix:"
echo "   ✅ TomTom: Working (already working)"
echo "   ✅ HERE: Should work with new API key"
echo "   ✅ MapQuest: Should work"
echo "   ✅ National Highways: Should work"
echo "   📊 Result: 3-4/4 sources working"
echo ""
echo "⚡ QUICK ALTERNATIVE: Use Render CLI to set env vars"
echo "   render env set TOMTOM_API_KEY=9rZJqtnfYpOzlqnypI97nFb5oX17SNzp"
echo "   render env set HERE_API_KEY=55brLMetn_8TR0ghfLG3xFfaObY9jhPpu0XEb-W4_KQ"
echo "   (if you have Render CLI installed)"
