services:
  # Backend API Service - Go Barry v3.0
  - type: web
    name: go-barry
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048 --optimize-for-size
      - key: PORT
        value: 10000
      # API Keys (set these in Render dashboard)
      - key: TOMTOM_API_KEY
        sync: false
      - key: MAPQUEST_API_KEY  
        sync: false
      - key: HERE_API_KEY
        sync: false
      - key: MAPBOX_API_KEY
        sync: false
      - key: NATIONAL_HIGHWAYS_API_KEY
        sync: false
    autoDeploy: false

  # Frontend Web App - Go Barry v3.0 Dashboard  
  - type: static
    name: barry-frontend
    buildCommand: cd Go_BARRY && npm install && npm run build:web
    staticPublishPath: Go_BARRY/dist
    plan: free
    envVars:
      - key: EXPO_PUBLIC_API_BASE_URL
        value: https://go-barry.onrender.com
    autoDeploy: false
