services:
  # Backend API Service - Go Barry v3.0
  - type: web
    name: go-barry
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=2048
      - key: PORT
        value: 10000
      # API Keys and Environment
      - key: TOMTOM_API_KEY
        sync: false
      - key: MAPQUEST_API_KEY  
        sync: false
      - key: HERE_API_KEY
        sync: false
      - key: MAPBOX_API_KEY
        sync: false
      - key: NATIONAL_HIGHWAYS_API_KEY
        sync: false
      # CORS Configuration for your domain
      - key: CORS_ORIGIN
        value: https://www.gobarry.co.uk,https://gobarry.co.uk
      - key: PRODUCTION_DOMAIN
        value: gobarry.co.uk
    autoDeploy: false

  # Frontend Web App - Go Barry v3.0 Dashboard  
  - type: static
    name: barry-frontend
    buildCommand: cd Go_BARRY && npm install && npm run build:web
    staticPublishPath: Go_BARRY/dist
    plan: free
    envVars:
      - key: EXPO_PUBLIC_API_BASE_URL
        value: https://api.gobarry.co.uk
    autoDeploy: false
