/**
 * Start of Service Report API
 * Handles generation and sending of daily operational reports
 */

import express from 'express';
import { createClient } from '@supabase/supabase-js';

const router = express.Router();

// Initialize Supabase client
const supabaseUrl = process.env.SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

/**
 * GET /api/disruptions/active
 * Get all active disruptions for report generation
 */
router.get('/active', async (req, res) => {
  try {
    const { data: disruptions, error } = await supabase
      .from('disruptions')
      .select(`
        id,
        source_id,
        source_type,
        title,
        description,
        location,
        coordinates,
        affected_routes,
        severity,
        status,
        created_at,
        last_updated,
        notes
      `)
      .eq('status', 'active')
      .order('created_at', { ascending: false });

    if (error) {
      console.error('Error fetching active disruptions:', error);
      return res.status(500).json({ 
        error: 'Failed to fetch active disruptions',
        details: error.message 
      });
    }

    // Transform data for frontend consumption
    const transformedDisruptions = disruptions.map(disruption => ({
      id: disruption.id,
      sourceId: disruption.source_id,
      type: disruption.source_type,
      title: disruption.title,
      description: disruption.description,
      location: {
        description: disruption.location,
        coordinates: disruption.coordinates || { lat: 0, lng: 0 }
      },
      affectedRoutes: disruption.affected_routes || [],
      severity: disruption.severity,
      status: disruption.status,
      startTime: disruption.created_at,
      lastUpdated: disruption.last_updated,
      notes: disruption.notes
    }));

    res.json(transformedDisruptions);
  } catch (error) {
    console.error('Error in GET /active:', error);
    res.status(500).json({ 
      error: 'Internal server error',
      details: error.message 
    });
  }
});

/**
 * POST /api/reports/start-of-service
 * Generate and send Start of Service Report
 */
router.post('/start-of-service', async (req, res) => {
  try {
    const { title, content, generatedBy, supervisorId, disruptionCount } = req.body;

    if (!title || !content || !generatedBy) {
      return res.status(400).json({ 
        error: 'Missing required fields: title, content, generatedBy' 
      });
    }

    // Store report in database
    const reportData = {
      id: `sos_report_${Date.now()}`,
      type: 'start_of_service',
      title,
      content,
      generated_by: generatedBy,
      supervisor_id: supervisorId,
      disruption_count: disruptionCount || 0,
      generated_at: new Date().toISOString(),
      status: 'generated'
    };

    // In a real implementation, you would:
    // 1. Store the report in a reports table
    // 2. Send via email to the distribution list
    // 3. Archive the report for historical reference

    // For now, we'll simulate the email sending
    await simulateEmailSending(reportData);

    // Log the report generation
    console.log(`Start of Service Report generated by ${generatedBy}:`, {
      title,
      disruptionCount,
      contentLength: content.length
    });

    res.json({
      success: true,
      reportId: reportData.id,
      message: 'Start of Service Report generated and sent successfully',
      reportData: {
        id: reportData.id,
        title: reportData.title,
        generatedBy: reportData.generated_by,
        generatedAt: reportData.generated_at,
        disruptionCount: reportData.disruption_count
      }
    });

  } catch (error) {
    console.error('Error generating Start of Service Report:', error);
    res.status(500).json({ 
      error: 'Failed to generate Start of Service Report',
      details: error.message 
    });
  }
});

/**
 * Simulate email sending (replace with actual email service)
 */
async function simulateEmailSending(reportData) {
  // Simulate delay
  await new Promise(resolve => setTimeout(resolve, 1000));

  // In production, this would integrate with:
  // - Microsoft Graph API for Outlook
  // - SendGrid, AWS SES, or similar service
  // - Internal email server

  const emailData = {
    to: [
      'smt@gonortheast.co.uk',
      'operations@gonortheast.co.uk',
      'barry.perryman@gonortheast.co.uk'
    ],
    subject: reportData.title,
    body: reportData.content,
    from: 'go-barry@gonortheast.co.uk',
    timestamp: new Date().toISOString()
  };

  console.log('Email sent (simulated):', {
    to: emailData.to,
    subject: emailData.subject,
    contentLength: emailData.body.length
  });

  return emailData;
}

/**
 * GET /api/reports/history
 * Get historical Start of Service Reports
 */
router.get('/history', async (req, res) => {
  try {
    const { limit = 50, offset = 0 } = req.query;

    // In production, this would query a reports table
    // For now, return empty array
    const reports = [];

    res.json({
      reports,
      total: 0,
      limit: parseInt(limit),
      offset: parseInt(offset)
    });

  } catch (error) {
    console.error('Error fetching report history:', error);
    res.status(500).json({ 
      error: 'Failed to fetch report history',
      details: error.message 
    });
  }
});

export default router;