/**
 * Assessment Summary Component
 * Provides a comprehensive summary of the breakdown assessment for Tracerit reporting
 * 
 * This component displays all relevant information from the assessment that drivers
 * need to complete their Tracerit forms accurately.
 */

import React from 'react';
import { FileText, Printer, Mail, CheckCircle, Download, Copy, AlertTriangle } from './icons.jsx';

const AssessmentSummary = ({ 
    assessmentData,
    vehicle,
    supervisor,
    decision,
    wizardType,
    onPrint,
    onEmail,
    onComplete
}) => {
    // Format date and time
    const assessmentDate = new Date();
    const formattedDate = assessmentDate.toLocaleDateString('en-GB');
    const formattedTime = assessmentDate.toLocaleTimeString('en-GB', { 
        hour: '2-digit', 
        minute: '2-digit' 
    });
    
    // Get decision color and icon
    const getDecisionStyle = (decision) => {
        const upperDecision = decision?.toUpperCase();
        switch (upperDecision) {
            case 'STOP':
                return {
                    bgColor: 'bg-red-500/20',
                    borderColor: 'border-red-400/50',
                    textColor: 'text-red-200',
                    icon: '🛑'
                };
            case 'AMBER':
                return {
                    bgColor: 'bg-amber-500/20',
                    borderColor: 'border-amber-400/30',
                    textColor: 'text-amber-200',
                    icon: '⚠️'
                };
            case 'CONTINUE':
                return {
                    bgColor: 'bg-green-500/20',
                    borderColor: 'border-green-400/30',
                    textColor: 'text-green-200',
                    icon: '✅'
                };
            default:
                return {
                    bgColor: 'bg-gray-500/20',
                    borderColor: 'border-gray-400/30',
                    textColor: 'text-gray-200',
                    icon: '📋'
                };
        }
    };
    
    const decisionStyle = getDecisionStyle(decision);
    
    // Copy summary to clipboard
    const copySummaryToClipboard = () => {
        const summaryText = generateTextSummary();
        navigator.clipboard.writeText(summaryText).then(() => {
            // Show success notification
            if (window.PushNotificationManager) {
                window.PushNotificationManager.showInAppNotification(
                    'Summary copied to clipboard',
                    'success'
                );
            }
        });
    };
    
    // Generate text summary for clipboard/email
    const generateTextSummary = () => {
        return `
GO NORTH EAST - BREAKDOWN ASSESSMENT SUMMARY
============================================

ASSESSMENT DETAILS
------------------
Date: ${formattedDate}
Time: ${formattedTime}
Assessment Type: ${wizardType}
Breakdown ID: ${assessmentData?.breakdownId || 'Pending'}

VEHICLE INFORMATION
-------------------
Fleet Number: ${vehicle?.fleetNumber || 'N/A'}
Registration: ${vehicle?.registration || 'N/A'}
Depot: ${vehicle?.depot || 'N/A'}
Type: ${vehicle?.type || 'N/A'}

LOCATION
--------
${assessmentData?.location?.address || 'Location not recorded'}
Coordinates: ${assessmentData?.location?.lat || 'N/A'}, ${assessmentData?.location?.lng || 'N/A'}

ASSESSMENT OUTCOME
------------------
Decision: ${decision?.toUpperCase() || 'N/A'}
${decision?.toUpperCase() === 'STOP' ? 'VEHICLE MUST NOT CONTINUE - Engineering attendance required immediately' : ''}
${decision?.toUpperCase() === 'AMBER' ? 'Vehicle may continue to safe changeover point - Arrange replacement ASAP' : ''}
${decision?.toUpperCase() === 'CONTINUE' ? 'Vehicle may remain in service - Monitor and log defect' : ''}

KEY FINDINGS
------------
${generateKeyFindings()}

ACTIONS TAKEN
-------------
${generateActionsList()}

SUPERVISOR DETAILS
------------------
Name: ${supervisor?.name || 'N/A'}
ID: ${supervisor?.supervisorId || 'N/A'}
Depot: ${supervisor?.depot || 'N/A'}

${wizardType?.toLowerCase().includes('road-traffic') || wizardType?.toLowerCase().includes('incident') ? `TRACERIT REQUIREMENTS
---------------------
- Log this assessment in Tracerit within 24 hours
- Include breakdown ID: ${assessmentData?.breakdownId || 'Pending'}
- Attach any photos taken during assessment
- Record all defects identified
- Note any safety concerns
${decision?.toUpperCase() === 'STOP' ? '- Mark as SAFETY CRITICAL in Tracerit' : ''}` : ''}

ADDITIONAL NOTES
----------------
${assessmentData?.notes || 'No additional notes recorded'}

---
Generated by Go North East Breakdown Guide
${new Date().toISOString()}
        `.trim();
    };
    
    // Generate key findings based on assessment responses
    const generateKeyFindings = () => {
        const findings = [];
        
        // Add specific findings based on wizard type and responses
        if (assessmentData?.responses) {
            Object.entries(assessmentData.responses).forEach(([key, value]) => {
                if (value === true || value === 'yes') {
                    findings.push(`- ${formatResponseKey(key)}: Confirmed`);
                } else if (typeof value === 'string' && value.length > 0 && value !== 'no') {
                    findings.push(`- ${formatResponseKey(key)}: ${value}`);
                }
            });
        }
        
        return findings.length > 0 ? findings.join('\n') : '- No specific defects identified';
    };
    
    // Generate actions list based on decision
    const generateActionsList = () => {
        const actions = [];
        const upperDecision = decision?.toUpperCase();
        
        switch (upperDecision) {
            case 'STOP':
                actions.push('- Vehicle stopped immediately');
                actions.push('- Engineering attendance requested');
                actions.push('- Passengers transferred if applicable');
                actions.push('- Area secured for safety');
                break;
            case 'AMBER':
                actions.push('- Changeover arranged at safe location');
                actions.push('- Engineering notified of defect');
                actions.push('- Driver briefed on limitations');
                actions.push('- Monitoring instructions provided');
                break;
            case 'CONTINUE':
                actions.push('- Defect logged for monitoring');
                actions.push('- Driver advised to remain vigilant');
                actions.push('- Scheduled for inspection at depot');
                break;
        }
        
        return actions.join('\n');
    };
    
    // Format response keys for display
    const formatResponseKey = (key) => {
        return key.replace(/_/g, ' ')
            .replace(/([A-Z])/g, ' $1')
            .trim()
            .split(' ')
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join(' ');
    };
    
    return (
        <div className="space-y-6">
            {/* Header */}
            <div className="text-center">
                <div className="mx-auto w-16 h-16 bg-blue-500/20 rounded-full flex items-center justify-center mb-4">
                    <FileText className="w-8 h-8 text-blue-400" />
                </div>
                <h2 className="text-2xl font-bold text-white mb-2">Assessment Summary</h2>
                <p className="text-gray-300">Complete summary for Tracerit reporting</p>
            </div>
            
            {/* Decision Banner */}
            <div className={`${decisionStyle.bgColor} backdrop-blur-sm rounded-lg p-6 border ${decisionStyle.borderColor}`}>
                <div className="text-center">
                    <div className="text-6xl mb-4">{decisionStyle.icon}</div>
                    <h3 className={`text-2xl font-bold mb-2 ${decisionStyle.textColor}`}>
                        {decision?.toUpperCase() || 'N/A'} DECISION
                    </h3>
                    <p className={`${decisionStyle.textColor} text-sm`}>
                        {decision?.toUpperCase() === 'STOP' && 'Vehicle must not continue - Immediate engineering required'}
                        {decision?.toUpperCase() === 'AMBER' && 'Continue to safe changeover point - Arrange replacement'}
                        {decision?.toUpperCase() === 'CONTINUE' && 'Vehicle may remain in service - Monitor defect'}
                    </p>
                </div>
            </div>
            
            {/* Quick Actions */}
            <div className="bg-blue-500/10 backdrop-blur-sm rounded-lg p-4 border border-blue-400/30">
                <h4 className="font-semibold text-blue-200 mb-3">Quick Actions</h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                    <button
                        onClick={copySummaryToClipboard}
                        className="flex items-center justify-center px-4 py-2 bg-blue-600/20 text-blue-200 rounded hover:bg-blue-600/30 transition-colors"
                    >
                        <Copy className="w-4 h-4 mr-2" />
                        Copy Summary
                    </button>
                    <button
                        onClick={onPrint}
                        className="flex items-center justify-center px-4 py-2 bg-blue-600/20 text-blue-200 rounded hover:bg-blue-600/30 transition-colors"
                    >
                        <Printer className="w-4 h-4 mr-2" />
                        Print Summary
                    </button>
                    <button
                        onClick={onEmail}
                        className="flex items-center justify-center px-4 py-2 bg-blue-600/20 text-blue-200 rounded hover:bg-blue-600/30 transition-colors"
                    >
                        <Mail className="w-4 h-4 mr-2" />
                        Email Summary
                    </button>
                </div>
            </div>
            
            {/* Assessment Details */}
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-6 border border-white/20">
                <h3 className="text-lg font-semibold text-white mb-4">Assessment Details</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                        <span className="text-gray-400">Date & Time:</span>
                        <span className="text-white ml-2">{formattedDate} at {formattedTime}</span>
                    </div>
                    <div>
                        <span className="text-gray-400">Assessment Type:</span>
                        <span className="text-white ml-2">{wizardType}</span>
                    </div>
                    <div>
                        <span className="text-gray-400">Breakdown ID:</span>
                        <span className="text-white ml-2">{assessmentData?.breakdownId || 'Pending'}</span>
                    </div>
                    <div>
                        <span className="text-gray-400">Supervisor:</span>
                        <span className="text-white ml-2">{supervisor?.name}</span>
                    </div>
                </div>
            </div>
            
            {/* Vehicle Information */}
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-6 border border-white/20">
                <h3 className="text-lg font-semibold text-white mb-4">Vehicle Information</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                    <div>
                        <span className="text-gray-400">Fleet Number:</span>
                        <span className="text-white ml-2">{vehicle?.fleetNumber}</span>
                    </div>
                    <div>
                        <span className="text-gray-400">Registration:</span>
                        <span className="text-white ml-2">{vehicle?.registration}</span>
                    </div>
                    <div>
                        <span className="text-gray-400">Depot:</span>
                        <span className="text-white ml-2">{vehicle?.depot}</span>
                    </div>
                    <div>
                        <span className="text-gray-400">Vehicle Type:</span>
                        <span className="text-white ml-2">{vehicle?.type}</span>
                    </div>
                </div>
            </div>
            
            {/* Key Findings */}
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-6 border border-white/20">
                <h3 className="text-lg font-semibold text-white mb-4">Key Findings</h3>
                <div className="space-y-2 text-sm">
                    {generateKeyFindings().split('\n').map((finding, index) => (
                        <div key={index} className="text-gray-300">
                            {finding}
                        </div>
                    ))}
                </div>
            </div>
            
            {/* Tracerit Reminder - Only shown for Road Traffic Incidents per SDC Guide */}
            {/* Only Road Traffic Incidents require Tracerit reports per SDC Guide */}
            {(wizardType?.toLowerCase().includes('road-traffic') || wizardType?.toLowerCase().includes('incident')) && (
                <div className="bg-purple-500/20 backdrop-blur-sm rounded-lg p-6 border border-purple-400/30">
                    <div className="flex items-start space-x-4">
                        <AlertTriangle className="w-6 h-6 text-purple-400 mt-1 flex-shrink-0" />
                        <div>
                            <h4 className="font-semibold text-purple-200 mb-2">Tracerit Reporting Requirements</h4>
                            <ul className="list-disc list-inside space-y-1 text-purple-300/90 text-sm">
                                <li>Complete Tracerit report within 24 hours</li>
                                <li>Include this breakdown ID: <span className="font-mono bg-black/30 px-1 rounded">{assessmentData?.breakdownId || 'Pending'}</span></li>
                                <li>Attach any photos taken during assessment</li>
                                <li>Record all defects identified above</li>
                                <li>Include location details and time of assessment</li>
                                {decision?.toUpperCase() === 'STOP' && <li className="text-red-300">Mark as SAFETY CRITICAL in Tracerit</li>}
                            </ul>
                        </div>
                    </div>
                </div>
            )}
            
            {/* Complete Assessment Button */}
            <div className="flex justify-center pt-6 border-t border-white/20">
                <button
                    onClick={onComplete}
                    className="flex items-center px-8 py-3 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
                >
                    <CheckCircle className="w-5 h-5 mr-2" />
                    Complete Assessment
                </button>
            </div>
        </div>
    );
};

export default AssessmentSummary;
